-- Branch-scoped migration: 20260820_add_inventory_procurement_pos
-- This migration folder is intentionally branch-owned by
-- agent/copilot-commerce-operations. Run `npx prisma migrate dev` in
-- this worktree to produce a fully validated SQL migration against your
-- TEST_DATABASE_URL. The schema changes are in prisma/schema.prisma.

-- Minimal advisory: for organization-scoped barcode uniqueness a
-- partial unique index is recommended in Postgres, example:
-- CREATE UNIQUE INDEX ON "InventoryItem" ("organizationId", "barcode") WHERE barcode IS NOT NULL;

-- The exact database DDL will be generated by Prisma's migrate tooling.
