import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { requireModuleAccess } from "@/lib/auth/module-access";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { listHotelSettings } from "@/modules/hotel/service";
import { upsertHotelSettingsAction } from "../actions";
export default async function HotelSettingsPage(){const tenant=await requireModuleAccess("hotel");const can=hasPermission(tenant,PERMISSIONS.HOTEL_SETTINGS_MANAGE);const properties=await listHotelSettings(tenant.organizationId);return <div className="space-y-6"><PageHeader title="Hotel Settings" description="Property check-in/out, tax, service-charge, and settlement policies."/><div className="space-y-4">{properties.map((p)=><form key={p.id} action={upsertHotelSettingsAction} className="grid gap-3 rounded-lg border p-4 sm:grid-cols-2 lg:grid-cols-6"><input type="hidden" name="propertyId" value={p.id}/><div className="font-medium lg:col-span-6">{p.name}</div><div><Label>Check-in</Label><Input name="checkInTime" type="time" defaultValue={p.settings?.checkInTime||"14:00"} disabled={!can}/></div><div><Label>Check-out</Label><Input name="checkOutTime" type="time" defaultValue={p.settings?.checkOutTime||"11:00"} disabled={!can}/></div><div><Label>Tax %</Label><Input name="taxRate" type="number" step="0.01" defaultValue={p.settings?.taxRate.toString()||"0"} disabled={!can}/></div><div><Label>Service %</Label><Input name="serviceChargeRate" type="number" step="0.01" defaultValue={p.settings?.serviceChargeRate.toString()||"0"} disabled={!can}/></div><label className="flex items-center gap-2 text-sm"><input name="allowOutstandingCheckout" type="checkbox" defaultChecked={p.settings?.allowOutstandingCheckout} disabled={!can}/>Allow outstanding checkout</label>{can?<Button size="sm">Save</Button>:null}</form>)}</div></div>}
