import { Receipt } from "lucide-react";
import { Prisma } from "@prisma/client";
import { PageHeader } from "@/components/layout/page-header";
import { EmptyState } from "@/components/feedback/empty-state";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { requireModuleAccess } from "@/lib/auth/module-access";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { listOpenHotelFolios } from "@/modules/hotel/service";
import { postFolioChargeAction, recordFolioPaymentAction } from "../actions";

export default async function HotelFoliosPage() { const tenant=await requireModuleAccess("hotel"); const canManage=hasPermission(tenant,PERMISSIONS.HOTEL_FOLIOS_MANAGE); const folios=await listOpenHotelFolios(tenant.organizationId); return <div className="space-y-6"><PageHeader title="Folios & Payments" description="Immutable stay charges, receipts, settlement, and outstanding balances." />{folios.length===0?<EmptyState icon={Receipt} title="No open folios" description="A folio is created automatically when a guest checks in."/>:<div className="space-y-4">{folios.map((folio)=>{const charges=folio.entries.reduce((s,e)=>s.plus(e.amount),new Prisma.Decimal(0));const paid=folio.payments.filter((p)=>!p.refundedAt).reduce((s,p)=>s.plus(p.amount),new Prisma.Decimal(0));return <div key={folio.id} className="rounded-lg border p-4"><div className="flex justify-between"><div><p className="font-medium">{folio.folioNumber} · {folio.reservation.guest.firstName} {folio.reservation.guest.lastName}</p><p className="text-sm text-muted-foreground">Room {folio.reservation.room?.number || "unassigned"}</p></div><p className="font-medium">Balance {charges.minus(paid).toFixed(2)}</p></div>{canManage?<div className="mt-4 grid gap-4 lg:grid-cols-2"><form action={postFolioChargeAction} className="grid gap-2 rounded-md border p-3"><input type="hidden" name="folioId" value={folio.id}/><Label>Post charge</Label><Input name="description" placeholder="Description" required/><Input name="amount" type="number" step="0.01" min="0.01" placeholder="Amount" required/><Input name="reference" placeholder="Reference"/><Button size="sm" type="submit">Post charge</Button></form><form action={recordFolioPaymentAction} className="grid gap-2 rounded-md border p-3"><input type="hidden" name="folioId" value={folio.id}/><Label>Record payment</Label><Input name="amount" type="number" step="0.01" min="0.01" placeholder="Amount" required/><select name="method" className="h-9 rounded-md border bg-transparent px-3 text-sm">{["CASH","CARD","MOBILE_MONEY","BANK_TRANSFER","ONLINE","OTHER"].map((v)=><option key={v}>{v}</option>)}</select><Input name="reference" placeholder="Reference"/><Button size="sm" type="submit">Record payment</Button></form></div>:null}</div>})}</div>}</div>; }
