import { Lock, ReceiptText } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { EmptyState } from "@/components/feedback/empty-state";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { requireModuleAccess } from "@/lib/auth/module-access";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { createOrganizationFormatter } from "@/lib/org-format";
import { listPayslips } from "@/modules/payroll/service";

export default async function PayrollPayslipsPage() {
  const tenant = await requireModuleAccess("payroll");
  const money = createOrganizationFormatter(tenant.organization).money;

  if (!hasPermission(tenant, PERMISSIONS.PAYROLL_PAYSLIPS_VIEW)) {
    return (
      <div className="space-y-6">
        <PageHeader title="Payslips" description="Every payslip generated by a completed payroll run." />
        <EmptyState icon={Lock} title="You don't have access to this page" description="Payslips are limited to roles with payslip-viewing permissions." />
      </div>
    );
  }

  const payslips = await listPayslips(tenant.organizationId);
  const currency = tenant.organization.currency;

  return (
    <div className="space-y-6">
      <PageHeader title="Payslips" description="Every payslip generated by a completed payroll run." />

      {payslips.length === 0 ? (
        <EmptyState icon={ReceiptText} title="No payslips yet" description="Payslips appear here once a payroll run is processed." />
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Employee</TableHead>
              <TableHead>Pay period</TableHead>
              <TableHead>Gross pay ({currency})</TableHead>
              <TableHead>Tax deduction ({currency})</TableHead>
              <TableHead>Other deductions ({currency})</TableHead>
              <TableHead>Net pay ({currency})</TableHead>
              <TableHead>Employer contributions ({currency})</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {payslips.map((slip) => (
              <TableRow key={slip.id}>
                <TableCell className="font-medium">{slip.employee.fullName}</TableCell>
                <TableCell className="text-muted-foreground">
                  {slip.payrollRun.periodStart.toLocaleDateString()} – {slip.payrollRun.periodEnd.toLocaleDateString()}
                </TableCell>
                <TableCell className="text-muted-foreground">{money(slip.grossPay, currency)}</TableCell>
                <TableCell className="text-muted-foreground">{money(slip.taxDeduction, currency)}</TableCell>
                <TableCell className="text-muted-foreground">
                  {money(slip.otherDeductions, currency)}
                  {slip.deductions.length ? (
                    <ul className="mt-1 space-y-0.5 text-xs">
                      {slip.deductions.filter((line) => line.kind !== "EMPLOYER_CONTRIBUTION").map((line) => <li key={line.id}>{line.name}: {money(line.amount, currency)}</li>)}
                    </ul>
                  ) : null}
                </TableCell>
                <TableCell className="font-medium">{money(slip.netPay, currency)}</TableCell>
                <TableCell className="text-muted-foreground">
                  {money(slip.employerContributions, currency)}
                  {slip.deductions.some((line) => line.kind === "EMPLOYER_CONTRIBUTION") ? (
                    <ul className="mt-1 space-y-0.5 text-xs">
                      {slip.deductions.filter((line) => line.kind === "EMPLOYER_CONTRIBUTION").map((line) => <li key={line.id}>{line.name}: {money(line.amount, currency)}</li>)}
                    </ul>
                  ) : null}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}
    </div>
  );
}
