import { ReceiptText } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { EmptyState } from "@/components/feedback/empty-state";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { requireCurrentTenant } from "@/lib/tenant";
import { listPayslips } from "@/modules/payroll/service";

export default async function PayrollPayslipsPage() {
  const tenant = await requireCurrentTenant();
  const payslips = await listPayslips(tenant.organizationId);

  return (
    <div className="space-y-6">
      <PageHeader title="Payslips" description="Every payslip generated by a completed payroll run." />

      {payslips.length === 0 ? (
        <EmptyState icon={ReceiptText} title="No payslips yet" description="Payslips appear here once a payroll run is processed." />
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Employee</TableHead>
              <TableHead>Pay period</TableHead>
              <TableHead>Gross pay</TableHead>
              <TableHead>Tax deduction</TableHead>
              <TableHead>Other deductions</TableHead>
              <TableHead>Net pay</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {payslips.map((slip) => (
              <TableRow key={slip.id}>
                <TableCell className="font-medium">{slip.employee.fullName}</TableCell>
                <TableCell className="text-muted-foreground">
                  {slip.payrollRun.periodStart.toLocaleDateString()} – {slip.payrollRun.periodEnd.toLocaleDateString()}
                </TableCell>
                <TableCell className="text-muted-foreground">{Number(slip.grossPay).toFixed(2)}</TableCell>
                <TableCell className="text-muted-foreground">{Number(slip.taxDeduction).toFixed(2)}</TableCell>
                <TableCell className="text-muted-foreground">{Number(slip.otherDeductions).toFixed(2)}</TableCell>
                <TableCell className="font-medium">{Number(slip.netPay).toFixed(2)}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}
    </div>
  );
}
