import { Lock, ReceiptText } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { EmptyState } from "@/components/feedback/empty-state";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { requireModuleAccess } from "@/lib/auth/module-access";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { listPayslips } from "@/modules/payroll/service";

export default async function PayrollPayslipsPage() {
  const tenant = await requireModuleAccess("payroll");

  if (!hasPermission(tenant, PERMISSIONS.PAYROLL_PAYSLIPS_VIEW)) {
    return (
      <div className="space-y-6">
        <PageHeader title="Payslips" description="Every payslip generated by a completed payroll run." />
        <EmptyState icon={Lock} title="You don't have access to this page" description="Payslips are limited to roles with payslip-viewing permissions." />
      </div>
    );
  }

  const payslips = await listPayslips(tenant.organizationId);

  return (
    <div className="space-y-6">
      <PageHeader title="Payslips" description="Every payslip generated by a completed payroll run." />

      {payslips.length === 0 ? (
        <EmptyState icon={ReceiptText} title="No payslips yet" description="Payslips appear here once a payroll run is processed." />
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Employee</TableHead>
              <TableHead>Pay period</TableHead>
              <TableHead>Gross pay</TableHead>
              <TableHead>Tax deduction</TableHead>
              <TableHead>Other deductions</TableHead>
              <TableHead>Net pay</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {payslips.map((slip) => (
              <TableRow key={slip.id}>
                <TableCell className="font-medium">{slip.employee.fullName}</TableCell>
                <TableCell className="text-muted-foreground">
                  {slip.payrollRun.periodStart.toLocaleDateString()} – {slip.payrollRun.periodEnd.toLocaleDateString()}
                </TableCell>
                <TableCell className="text-muted-foreground">{Number(slip.grossPay).toFixed(2)}</TableCell>
                <TableCell className="text-muted-foreground">{Number(slip.taxDeduction).toFixed(2)}</TableCell>
                <TableCell className="text-muted-foreground">{Number(slip.otherDeductions).toFixed(2)}</TableCell>
                <TableCell className="font-medium">{Number(slip.netPay).toFixed(2)}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}
    </div>
  );
}
