"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireModuleAccess } from "@/lib/auth/module-access";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { cuid, shortText, longText, dateInput, moneyAmountPositive, parseWithSchema } from "@/lib/validation";
import { createSchoolCampus, createSchoolAcademicYear, createSchoolTerm, createSchoolStudent, createSchoolGuardian, linkSchoolGuardian, createSchoolClass, createSchoolSubject, enrollSchoolStudent, recordSchoolAttendance, createSchoolFeeInvoice, recordSchoolFeePayment, createSchoolTimetableEntry, createSchoolExam, recordSchoolExamResult, submitSchoolExamForModeration, publishSchoolExam, createSchoolLibraryBook, borrowSchoolLibraryBook, returnSchoolLibraryBook, createSchoolTransportRoute, assignSchoolTransport, createSchoolPayrollAdjustment, upsertSchoolSettings, SchoolStateError, SchoolNotFoundError } from "@/modules/school/service";

const clean=(value:FormDataEntryValue|null)=>{const text=String(value??"").trim();return text||null};
async function auth(permission:string,path:string){const tenant=await requireModuleAccess("school");if(!hasPermission(tenant,permission))redirect(`${path}?error=forbidden`);return tenant;}
const fail=(path:string,error:unknown)=>{if(error instanceof SchoolStateError)redirect(`${path}?error=state`);if(error instanceof SchoolNotFoundError)redirect(`${path}?error=not-found`);throw error;};

export async function createCampusAction(f:FormData){const path="/app/school/campuses",t=await auth(PERMISSIONS.SCHOOL_CAMPUSES_MANAGE,path);const p=z.object({code:shortText,name:shortText,address:longText.nullable(),phone:shortText.nullable(),email:z.string().email().nullable()}).safeParse({code:clean(f.get("code")),name:clean(f.get("name")),address:clean(f.get("address")),phone:clean(f.get("phone")),email:clean(f.get("email"))});if(!p.success)redirect(`${path}?error=invalid`);await createSchoolCampus(t.organizationId,p.data);revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createAcademicYearAction(f:FormData){const path="/app/school/academic-periods",t=await auth(PERMISSIONS.SCHOOL_ACADEMICS_MANAGE,path);const p=parseWithSchema(z.object({name:shortText,startDate:dateInput,endDate:dateInput,current:z.boolean()}),{name:clean(f.get("name"))??"",startDate:clean(f.get("startDate")),endDate:clean(f.get("endDate")),current:f.get("current")==="on"});if(!p.success)redirect(`${path}?error=invalid`);try{await createSchoolAcademicYear(t.organizationId,p.data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createTermAction(f:FormData){const path="/app/school/academic-periods",t=await auth(PERMISSIONS.SCHOOL_ACADEMICS_MANAGE,path);const p=parseWithSchema(z.object({academicYearId:cuid,name:shortText,startDate:dateInput,endDate:dateInput,current:z.boolean()}),{academicYearId:clean(f.get("academicYearId"))??"",name:clean(f.get("name"))??"",startDate:clean(f.get("startDate")),endDate:clean(f.get("endDate")),current:f.get("current")==="on"});if(!p.success)redirect(`${path}?error=invalid`);try{await createSchoolTerm(t.organizationId,p.data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createStudentAction(f:FormData){const path="/app/school/students",t=await auth(PERMISSIONS.SCHOOL_STUDENTS_MANAGE,path);const p=parseWithSchema(z.object({campusId:cuid,firstName:shortText,lastName:shortText,dateOfBirth:dateInput.nullable(),gender:shortText.nullable(),admissionDate:dateInput.nullable(),medicalNotes:longText.nullable()}),{campusId:clean(f.get("campusId"))??"",firstName:clean(f.get("firstName"))??"",lastName:clean(f.get("lastName"))??"",dateOfBirth:clean(f.get("dateOfBirth")),gender:clean(f.get("gender")),admissionDate:clean(f.get("admissionDate")),medicalNotes:clean(f.get("medicalNotes"))});if(!p.success)redirect(`${path}?error=invalid`);try{await createSchoolStudent(t.organizationId,p.data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createGuardianAction(f:FormData){const path="/app/school/students",t=await auth(PERMISSIONS.SCHOOL_STUDENTS_MANAGE,path);const p=z.object({firstName:shortText,lastName:shortText,email:z.string().email().nullable(),phone:shortText,address:longText.nullable(),occupation:shortText.nullable()}).safeParse({firstName:clean(f.get("firstName")),lastName:clean(f.get("lastName")),email:clean(f.get("email")),phone:clean(f.get("phone")),address:clean(f.get("address")),occupation:clean(f.get("occupation"))});if(!p.success)redirect(`${path}?error=invalid`);await createSchoolGuardian(t.organizationId,p.data);revalidatePath(path);redirect(`${path}?saved=1`)}
export async function linkGuardianAction(f:FormData){const path="/app/school/students",t=await auth(PERMISSIONS.SCHOOL_STUDENTS_MANAGE,path);const p=z.object({studentId:cuid,guardianId:cuid,relationship:shortText,primary:z.boolean()}).safeParse({studentId:clean(f.get("studentId")),guardianId:clean(f.get("guardianId")),relationship:clean(f.get("relationship")),primary:f.get("primary")==="on"});if(!p.success)redirect(`${path}?error=invalid`);try{await linkSchoolGuardian(t.organizationId,p.data.studentId,p.data.guardianId,p.data.relationship,p.data.primary)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createClassAction(f:FormData){const path="/app/school/classes",t=await auth(PERMISSIONS.SCHOOL_ACADEMICS_MANAGE,path);const p=z.object({campusId:cuid,code:shortText,name:shortText,gradeLevel:shortText.nullable(),capacity:z.coerce.number().int().positive().max(10000).nullable()}).safeParse({campusId:clean(f.get("campusId")),code:clean(f.get("code")),name:clean(f.get("name")),gradeLevel:clean(f.get("gradeLevel")),capacity:clean(f.get("capacity"))?clean(f.get("capacity")):null});if(!p.success)redirect(`${path}?error=invalid`);await createSchoolClass(t.organizationId,p.data);revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createSubjectAction(f:FormData){const path="/app/school/classes",t=await auth(PERMISSIONS.SCHOOL_ACADEMICS_MANAGE,path);const p=z.object({code:shortText,name:shortText,description:longText.nullable()}).safeParse({code:clean(f.get("code")),name:clean(f.get("name")),description:clean(f.get("description"))});if(!p.success)redirect(`${path}?error=invalid`);await createSchoolSubject(t.organizationId,p.data);revalidatePath(path);redirect(`${path}?saved=1`)}
export async function enrollStudentAction(f:FormData){const path="/app/school/classes",t=await auth(PERMISSIONS.SCHOOL_ENROLLMENT_MANAGE,path);const p=z.object({campusId:cuid,academicYearId:cuid,studentId:cuid,classId:cuid}).safeParse(Object.fromEntries(["campusId","academicYearId","studentId","classId"].map(k=>[k,clean(f.get(k))])));if(!p.success)redirect(`${path}?error=invalid`);try{await enrollSchoolStudent(t.organizationId,p.data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function recordAttendanceAction(f:FormData){const path="/app/school/attendance",t=await auth(PERMISSIONS.SCHOOL_ATTENDANCE_MANAGE,path);const p=parseWithSchema(z.object({termId:cuid,classId:cuid,studentId:cuid,date:dateInput,status:z.enum(["PRESENT","ABSENT","LATE","EXCUSED"]),reason:shortText.nullable()}),{termId:clean(f.get("termId"))??"",classId:clean(f.get("classId"))??"",studentId:clean(f.get("studentId"))??"",date:clean(f.get("date")),status:clean(f.get("status")),reason:clean(f.get("reason"))});if(!p.success)redirect(`${path}?error=invalid`);try{await recordSchoolAttendance(t.organizationId,p.data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createFeeInvoiceAction(f:FormData){const path="/app/school/fees",t=await auth(PERMISSIONS.SCHOOL_FEES_MANAGE,path);const p=parseWithSchema(z.object({academicYearId:cuid,termId:cuid.nullable(),studentId:cuid,description:shortText,amount:moneyAmountPositive,discount:z.coerce.number().min(0),dueDate:dateInput.nullable()}),{academicYearId:clean(f.get("academicYearId"))??"",termId:clean(f.get("termId")),studentId:clean(f.get("studentId"))??"",description:clean(f.get("description"))??"",amount:clean(f.get("amount")),discount:clean(f.get("discount"))??"0",dueDate:clean(f.get("dueDate"))});if(!p.success)redirect(`${path}?error=invalid`);try{await createSchoolFeeInvoice(t.organizationId,p.data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function recordFeePaymentAction(f:FormData){const path="/app/school/fees",t=await auth(PERMISSIONS.SCHOOL_FEES_MANAGE,path);const p=parseWithSchema(z.object({invoiceId:cuid,amount:moneyAmountPositive,method:z.enum(["CASH","CARD","MOBILE_MONEY","BANK_TRANSFER","ONLINE","OTHER"]),reference:shortText.nullable()}),{invoiceId:clean(f.get("invoiceId"))??"",amount:clean(f.get("amount")),method:clean(f.get("method")),reference:clean(f.get("reference"))});if(!p.success)redirect(`${path}?error=invalid`);const{invoiceId,...data}=p.data;try{await recordSchoolFeePayment(t.organizationId,invoiceId,data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createTimetableAction(f:FormData){const path="/app/school/timetables",t=await auth(PERMISSIONS.SCHOOL_TIMETABLES_MANAGE,path);const p=z.object({campusId:cuid,termId:cuid,classId:cuid,subjectId:cuid,teacherName:shortText,room:shortText.nullable(),dayOfWeek:z.coerce.number().int().min(1).max(7),startsAt:shortText,endsAt:shortText}).safeParse(Object.fromEntries(["campusId","termId","classId","subjectId","teacherName","room","dayOfWeek","startsAt","endsAt"].map(k=>[k,clean(f.get(k))])));if(!p.success)redirect(`${path}?error=invalid`);try{await createSchoolTimetableEntry(t.organizationId,p.data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createExamAction(f:FormData){const path="/app/school/exams",t=await auth(PERMISSIONS.SCHOOL_EXAMS_MANAGE,path);const p=parseWithSchema(z.object({academicYearId:cuid,termId:cuid,subjectId:cuid,name:shortText,totalMarks:moneyAmountPositive,weight:moneyAmountPositive,examDate:dateInput.nullable()}),{academicYearId:clean(f.get("academicYearId"))??"",termId:clean(f.get("termId"))??"",subjectId:clean(f.get("subjectId"))??"",name:clean(f.get("name"))??"",totalMarks:clean(f.get("totalMarks")),weight:clean(f.get("weight")),examDate:clean(f.get("examDate"))});if(!p.success)redirect(`${path}?error=invalid`);try{await createSchoolExam(t.organizationId,p.data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function recordExamResultAction(f:FormData){const path="/app/school/exams",t=await auth(PERMISSIONS.SCHOOL_EXAMS_MANAGE,path);const p=z.object({examId:cuid,studentId:cuid,classId:cuid,subjectId:cuid,marks:z.coerce.number().min(0),grade:shortText.nullable(),remark:shortText.nullable()}).safeParse(Object.fromEntries(["examId","studentId","classId","subjectId","marks","grade","remark"].map(k=>[k,clean(f.get(k))])));if(!p.success)redirect(`${path}?error=invalid`);try{await recordSchoolExamResult(t.organizationId,p.data)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function submitExamForModerationAction(f:FormData){const path="/app/school/exams",t=await auth(PERMISSIONS.SCHOOL_EXAMS_MANAGE,path);const id=clean(f.get("examId"));if(!id)redirect(`${path}?error=invalid`);try{await submitSchoolExamForModeration(t.organizationId,id)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function publishExamAction(f:FormData){const path="/app/school/exams",t=await auth(PERMISSIONS.SCHOOL_EXAMS_PUBLISH,path);const id=clean(f.get("examId"));if(!id)redirect(`${path}?error=invalid`);try{await publishSchoolExam(t.organizationId,id)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createLibraryBookAction(f:FormData){const path="/app/school/library",t=await auth(PERMISSIONS.SCHOOL_LIBRARY_MANAGE,path);const p=z.object({accessionCode:shortText,isbn:shortText.nullable(),title:shortText,author:shortText.nullable(),category:shortText.nullable(),totalCopies:z.coerce.number().int().min(1).max(10000)}).safeParse(Object.fromEntries(["accessionCode","isbn","title","author","category","totalCopies"].map(k=>[k,clean(f.get(k))])));if(!p.success)redirect(`${path}?error=invalid`);await createSchoolLibraryBook(t.organizationId,p.data);revalidatePath(path);redirect(`${path}?saved=1`)}
export async function borrowBookAction(f:FormData){const path="/app/school/library",t=await auth(PERMISSIONS.SCHOOL_LIBRARY_MANAGE,path);const p=parseWithSchema(z.object({bookId:cuid,studentId:cuid,dueAt:dateInput}),{bookId:clean(f.get("bookId"))??"",studentId:clean(f.get("studentId"))??"",dueAt:clean(f.get("dueAt"))});if(!p.success)redirect(`${path}?error=invalid`);try{await borrowSchoolLibraryBook(t.organizationId,p.data.bookId,p.data.studentId,p.data.dueAt)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function returnBookAction(f:FormData){const path="/app/school/library",t=await auth(PERMISSIONS.SCHOOL_LIBRARY_MANAGE,path);const id=clean(f.get("loanId"));if(!id)redirect(`${path}?error=invalid`);try{await returnSchoolLibraryBook(t.organizationId,id)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createTransportRouteAction(f:FormData){const path="/app/school/transport",t=await auth(PERMISSIONS.SCHOOL_TRANSPORT_MANAGE,path);const p=z.object({campusId:cuid,code:shortText,name:shortText,vehicle:shortText.nullable(),driverName:shortText.nullable(),stops:shortText.nullable(),fee:z.coerce.number().min(0)}).safeParse(Object.fromEntries(["campusId","code","name","vehicle","driverName","stops","fee"].map(k=>[k,clean(f.get(k))])));if(!p.success)redirect(`${path}?error=invalid`);const{stops,...data}=p.data;try{await createSchoolTransportRoute(t.organizationId,{...data,stops:stops?.split(",").map(s=>s.trim()).filter(Boolean)})}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function assignTransportAction(f:FormData){const path="/app/school/transport",t=await auth(PERMISSIONS.SCHOOL_TRANSPORT_MANAGE,path);const p=z.object({routeId:cuid,studentId:cuid,stopName:shortText.nullable()}).safeParse({routeId:clean(f.get("routeId")),studentId:clean(f.get("studentId")),stopName:clean(f.get("stopName"))});if(!p.success)redirect(`${path}?error=invalid`);try{await assignSchoolTransport(t.organizationId,p.data.routeId,p.data.studentId,p.data.stopName)}catch(e){fail(path,e)}revalidatePath(path);redirect(`${path}?saved=1`)}
export async function createPayrollAdjustmentAction(f:FormData){const path="/app/school/payroll",t=await auth(PERMISSIONS.SCHOOL_PAYROLL_MANAGE,path);const p=parseWithSchema(z.object({employeeId:shortText,period:shortText,type:shortText,description:shortText,amount:moneyAmountPositive}),Object.fromEntries(["employeeId","period","type","description","amount"].map(k=>[k,clean(f.get(k))??""])));if(!p.success)redirect(`${path}?error=invalid`);await createSchoolPayrollAdjustment(t.organizationId,p.data);revalidatePath(path);redirect(`${path}?saved=1`)}
export async function upsertSchoolSettingsAction(f:FormData){const path="/app/school/settings",t=await auth(PERMISSIONS.SCHOOL_SETTINGS_MANAGE,path);const p=z.object({campusId:cuid,attendanceCloseDays:z.coerce.number().int().min(0).max(365),receiptPrefix:shortText,allowRanking:z.boolean(),gradingScaleText:longText.nullable()}).safeParse({campusId:clean(f.get("campusId")),attendanceCloseDays:clean(f.get("attendanceCloseDays")),receiptPrefix:clean(f.get("receiptPrefix")),allowRanking:f.get("allowRanking")==="on",gradingScaleText:clean(f.get("gradingScaleText"))});if(!p.success)redirect(`${path}?error=invalid`);let gradingScale;try{gradingScale=p.data.gradingScaleText?JSON.parse(p.data.gradingScaleText):undefined}catch{redirect(`${path}?error=invalid`)}await upsertSchoolSettings(t.organizationId,{campusId:p.data.campusId,attendanceCloseDays:p.data.attendanceCloseDays,receiptPrefix:p.data.receiptPrefix,allowRanking:p.data.allowRanking,gradingScale});revalidatePath(path);redirect(`${path}?saved=1`)}
