import { LayoutGrid, Banknote, PlayCircle, ReceiptText, BarChart3, Settings } from "lucide-react";
import type { ModuleNavItem } from "@/types/module";

export const payrollNavigation: ModuleNavItem[] = [
  { label: "Payroll Overview", href: "/app/payroll", icon: <LayoutGrid className="size-4" />, description: "See employees on payroll, missing compensation, draft runs, and last run's net pay at a glance." },
  { label: "Compensation", href: "/app/payroll/compensation", icon: <Banknote className="size-4" />, description: "Add payroll employees and set their base salary and pay frequency." },
  { label: "Runs", href: "/app/payroll/runs", icon: <PlayCircle className="size-4" />, description: "Create, process, or cancel payroll runs that pay every active employee with compensation on file." },
  { label: "Payslips", href: "/app/payroll/payslips", icon: <ReceiptText className="size-4" />, description: "View gross pay, deductions, and net pay for every payslip generated by a completed run." },
  { label: "Reports", href: "/app/payroll/reports", icon: <BarChart3 className="size-4" />, description: "View payroll coverage, run counts, and gross and net pay totals from the last run, and export them." },
  { label: "Payroll Settings", href: "/app/payroll/settings", icon: <Settings className="size-4" />, description: "Set the default flat tax rate applied to gross pay when a run is processed." },
];
