import { UtensilsCrossed } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { EmptyState } from "@/components/feedback/empty-state";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { requireModuleAccess } from "@/lib/auth/module-access";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { formatMoney } from "@/lib/currency";
import { listHotelProperties, listHotelRestaurantData, listOpenHotelFolios } from "@/modules/hotel/service";
import { createMenuItemAction, createOrderAction, createOutletAction } from "../actions";

const Select=({name,options}:{name:string;options:[string,string][]})=><select name={name} required className="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Select…</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>;
export default async function HotelRestaurantPage(){const tenant=await requireModuleAccess("hotel");const can=hasPermission(tenant,PERMISSIONS.HOTEL_RESTAURANT_MANAGE);const [[outlets,orders],properties,folios]=await Promise.all([listHotelRestaurantData(tenant.organizationId),listHotelProperties(tenant.organizationId),listOpenHotelFolios(tenant.organizationId)]);const items=outlets.flatMap((o)=>o.menuItems.map((i)=>[i.id,`${o.name} · ${i.name}`] as [string,string]));return <div className="space-y-6"><PageHeader title="Restaurant" description="Outlets, menus, food-and-beverage orders, room service, and folio charging."/>{can?<div className="grid gap-4 lg:grid-cols-3"><form action={createOutletAction} className="grid gap-2 rounded-lg border p-4"><Label>New outlet</Label><Select name="propertyId" options={properties.map((p)=>[p.id,p.name])}/><Input name="name" placeholder="Outlet name" required/><Button size="sm">Create outlet</Button></form><form action={createMenuItemAction} className="grid gap-2 rounded-lg border p-4"><Label>New menu item</Label><Select name="outletId" options={outlets.map((o)=>[o.id,o.name])}/><Input name="name" placeholder="Item" required/><Input name="category" placeholder="Category"/><Input name="price" type="number" step="0.01" min="0.01" placeholder={`Price (${tenant.organization.currency ?? "GHS"})`} required/><Button size="sm">Create item</Button></form><form action={createOrderAction} className="grid gap-2 rounded-lg border p-4"><Label>New order</Label><Select name="outletId" options={outlets.map((o)=>[o.id,o.name])}/><Select name="menuItemId" options={items}/><select name="folioId" className="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">No room folio</option>{folios.map((f)=><option key={f.id} value={f.id}>{f.folioNumber}</option>)}</select><Input name="tableOrRoom" placeholder="Table or room"/><Input name="quantity" type="number" min="1" defaultValue="1" required/><Button size="sm">Open order</Button></form></div>:null}{outlets.length===0?<EmptyState icon={UtensilsCrossed} title="No restaurant outlets" description="Create an outlet, menu items, then orders."/>:<div className="grid gap-4 md:grid-cols-2">{outlets.map((outlet)=><div key={outlet.id} className="rounded-lg border p-4"><p className="font-medium">{outlet.name}</p><p className="text-sm text-muted-foreground">{outlet.menuItems.length} menu items</p></div>)}</div>}<div className="space-y-2">{orders.map((order)=><div key={order.id} className="flex justify-between rounded-lg border p-3"><span>{order.orderNumber} · {order.outlet.name}</span><span className="text-sm text-muted-foreground">{order.status} · {formatMoney(order.total, tenant.organization.currency)}</span></div>)}</div></div>}
