"use client";

import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { captureOfflineOperation } from "@/lib/pwa/offline-capture";
import type { OfflineWorkPack } from "@/lib/pwa/types";

type JsonObject = Record<string, unknown>;
function object(value: unknown): JsonObject | null { return value && typeof value === "object" && !Array.isArray(value) ? value as JsonObject : null; }
function array(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function string(value: unknown) { return typeof value === "string" ? value : ""; }
function version(value: unknown, fallback: number) { const parsed = Date.parse(string(value)); return Number.isFinite(parsed) ? parsed : fallback; }
function packRecords(workPacks: OfflineWorkPack[], module: string) { return workPacks.filter((pack) => pack.module === module).sort((a, b) => b.downloadedAt.localeCompare(a.downloadedAt))[0]?.records ?? []; }
function kindValue(records: unknown[], kind: string) { return object(records.find((record) => object(record)?.kind === kind))?.value; }

export function OfflineOperationalCapture({ organizationId, userId, workPacks, onSaved }: { organizationId: string; userId: string; workPacks: OfflineWorkPack[]; onSaved(): Promise<void> }) {
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [fleetVehicle, setFleetVehicle] = useState("");
  const [fleetFault, setFleetFault] = useState("");
  const [fleetFiles, setFleetFiles] = useState<File[]>([]);
  const [fleetAmount, setFleetAmount] = useState("");
  const [fleetPeriod, setFleetPeriod] = useState("");
  const [fleetMethod, setFleetMethod] = useState("CASH");
  const [fleetReference, setFleetReference] = useState("");
  const [ownerRequest, setOwnerRequest] = useState("");
  const [ownerApproved, setOwnerApproved] = useState("true");
  const [countLine, setCountLine] = useState("");
  const [countQuantity, setCountQuantity] = useState("");
  const [schoolClass, setSchoolClass] = useState("");
  const [schoolTerm, setSchoolTerm] = useState("");
  const [schoolStudent, setSchoolStudent] = useState("");
  const [schoolDate, setSchoolDate] = useState("");
  const [attendanceStatus, setAttendanceStatus] = useState("PRESENT");
  const [housekeepingTask, setHousekeepingTask] = useState("");
  const [housekeepingStatus, setHousekeepingStatus] = useState("IN_PROGRESS");

  const fleetPack = useMemo(() => workPacks.filter((pack) => pack.module === "fleet").sort((a, b) => b.downloadedAt.localeCompare(a.downloadedAt))[0], [workPacks]);
  const fleetWorkspace = object(object(packRecords(workPacks, "fleet").find((record) => object(record)?.kind === "driver-workspace"))?.value);
  const vehicles = array(fleetWorkspace?.assignedVehicles).map(object).filter((item): item is JsonObject => Boolean(item));
  const ownerWorkspace = object(object(packRecords(workPacks, "fleet").find((record) => object(record)?.kind === "owner-workspace"))?.value);
  const ownerRequests = array(ownerWorkspace?.vehicles).map(object).filter((item): item is JsonObject => Boolean(item)).flatMap((vehicle) => array(vehicle.maintenanceRequests).map(object).filter((request): request is JsonObject => Boolean(request)).filter((request) => request.ownerApprovalRequired === true && request.ownerApprovalStatus === "PENDING"));
  const countPack = useMemo(() => workPacks.filter((pack) => pack.module === "inventory").sort((a, b) => b.downloadedAt.localeCompare(a.downloadedAt))[0], [workPacks]);
  const counts = array(kindValue(packRecords(workPacks, "inventory"), "draft-counts")).map(object).filter((item): item is JsonObject => Boolean(item));
  const countLines = counts.flatMap((count) => array(count.lines).map(object).filter((line): line is JsonObject => Boolean(line)).map((line) => ({ count, line })));
  const schoolPack = useMemo(() => workPacks.filter((pack) => pack.module === "school").sort((a, b) => b.downloadedAt.localeCompare(a.downloadedAt))[0], [workPacks]);
  const classes = array(kindValue(packRecords(workPacks, "school"), "classes")).map(object).filter((item): item is JsonObject => Boolean(item));
  const terms = array(kindValue(packRecords(workPacks, "school"), "terms")).map(object).filter((item): item is JsonObject => Boolean(item));
  const selectedClass = classes.find((item) => item.id === schoolClass);
  const students = array(selectedClass?.enrollments).map((entry) => object(object(entry)?.student)).filter((item): item is JsonObject => Boolean(item));
  const hotelPack = useMemo(() => workPacks.filter((pack) => pack.module === "hotel").sort((a, b) => b.downloadedAt.localeCompare(a.downloadedAt))[0], [workPacks]);
  const tasks = array(kindValue(packRecords(workPacks, "hotel"), "housekeeping")).map(object).filter((item): item is JsonObject => Boolean(item));

  async function save(work: () => Promise<unknown>, success: string) { setBusy(true); setMessage(null); try { await work(); setMessage(success); await onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "The action could not be saved offline."); } finally { setBusy(false); } }

  return <section className="space-y-4" aria-labelledby="operational-offline-heading">
    <div><h2 id="operational-offline-heading" className="text-lg font-semibold">Operational offline capture</h2><p className="text-sm text-muted-foreground">These actions remain pending until the server revalidates the downloaded work pack, permission, assignment, stock, and workflow state.</p></div>
    {message ? <p role="status" aria-live="polite" className="rounded-lg border p-3 text-sm">{message}</p> : null}
    {fleetPack ? <div className="grid gap-4 lg:grid-cols-2"><form className="space-y-3 rounded-lg border p-4" onSubmit={(event) => { event.preventDefault(); const vehicle = vehicles.find((item) => item.id === fleetVehicle); void save(() => captureOfflineOperation(organizationId, userId, { module: "fleet", entityType: "fleet.fault-report", entityId: crypto.randomUUID(), operationType: "report", baseServerVersion: version(vehicle?.updatedAt, fleetPack.serverVersion), payloadSchemaVersion: 1, payload: { vehicleId: fleetVehicle, faultDescription: fleetFault }, attachmentReferences: [], dependencyIds: [] }, fleetFiles), "Fault report saved locally. It is awaiting manager review after synchronization."); }}><h3 className="font-medium">Fleet fault report</h3><select className="w-full rounded-md border bg-background p-2" value={fleetVehicle} onChange={(event) => setFleetVehicle(event.target.value)} required><option value="">Choose assigned vehicle</option>{vehicles.map((vehicle) => <option key={string(vehicle.id)} value={string(vehicle.id)}>{string(vehicle.plateNumber) || string(vehicle.id)}</option>)}</select><Textarea value={fleetFault} onChange={(event) => setFleetFault(event.target.value)} placeholder="Describe the fault" required /><Input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => setFleetFiles(Array.from(event.target.files ?? []))} /><Button disabled={busy}>Save fault report for later</Button></form>
    <form className="space-y-3 rounded-lg border p-4" onSubmit={(event) => { event.preventDefault(); void save(() => captureOfflineOperation(organizationId, userId, { module: "fleet", entityType: "fleet.driver-payment", entityId: crypto.randomUUID(), operationType: "declare", baseServerVersion: fleetPack.serverVersion, payloadSchemaVersion: 1, payload: { vehicleId: fleetVehicle, submissionType: "DAILY_SALES", periodStart: new Date(`${fleetPeriod}T00:00:00.000Z`).toISOString(), amount: fleetAmount, paymentDate: new Date().toISOString(), paymentMethod: fleetMethod, reference: fleetReference || null }, attachmentReferences: [], dependencyIds: [] }), "Payment declaration recorded offline. It is not verified or paid until server confirmation."); }}><h3 className="font-medium">Fleet payment declaration</h3><select className="w-full rounded-md border bg-background p-2" value={fleetVehicle} onChange={(event) => setFleetVehicle(event.target.value)} required><option value="">Choose assigned vehicle</option>{vehicles.map((vehicle) => <option key={string(vehicle.id)} value={string(vehicle.id)}>{string(vehicle.plateNumber) || string(vehicle.id)}</option>)}</select><Input type="date" value={fleetPeriod} onChange={(event) => setFleetPeriod(event.target.value)} required /><Input inputMode="decimal" value={fleetAmount} onChange={(event) => setFleetAmount(event.target.value)} placeholder="Amount" required /><select className="w-full rounded-md border bg-background p-2" value={fleetMethod} onChange={(event) => setFleetMethod(event.target.value)}>{["CASH", "MOBILE_MONEY", "BANK_TRANSFER", "CARD", "CHEQUE", "OTHER"].map((method) => <option key={method}>{method}</option>)}</select>{fleetMethod !== "CASH" ? <Input value={fleetReference} onChange={(event) => setFleetReference(event.target.value)} placeholder="Transaction reference" required /> : null}<Button disabled={busy}>Record offline, awaiting verification</Button></form>
    {ownerRequests.length ? <form className="space-y-3 rounded-lg border p-4 lg:col-span-2" onSubmit={(event) => { event.preventDefault(); const request = ownerRequests.find((item) => item.id === ownerRequest); if (!request) return; void save(() => captureOfflineOperation(organizationId, userId, { module: "fleet", entityType: "fleet.owner-maintenance-decision", entityId: ownerRequest, operationType: "decide", baseServerVersion: version(request.updatedAt, fleetPack.serverVersion), payloadSchemaVersion: 1, payload: { requestId: ownerRequest, approved: ownerApproved === "true" }, attachmentReferences: [], dependencyIds: [] }), "Owner decision saved locally. It remains pending until the server confirms the workflow and permission."); }}><h3 className="font-medium">Vehicle owner maintenance decision</h3><select className="w-full rounded-md border bg-background p-2" value={ownerRequest} onChange={(event) => setOwnerRequest(event.target.value)} required><option value="">Choose request awaiting owner approval</option>{ownerRequests.map((request) => <option key={string(request.id)} value={string(request.id)}>{string(request.faultDescription) || string(request.id)}</option>)}</select><select className="w-full rounded-md border bg-background p-2" value={ownerApproved} onChange={(event) => setOwnerApproved(event.target.value)}><option value="true">Approve pending server confirmation</option><option value="false">Reject pending server confirmation</option></select><Button disabled={busy}>Save pending owner decision</Button></form> : null}</div> : null}
    {countPack ? <form className="space-y-3 rounded-lg border p-4" onSubmit={(event) => { event.preventDefault(); const selected = countLines.find(({ line }) => line.id === countLine); if (!selected) return; void save(() => captureOfflineOperation(organizationId, userId, { module: "inventory", entityType: "inventory.count-line", entityId: countLine, operationType: "count", baseServerVersion: version(selected.line.updatedAt, countPack.serverVersion), payloadSchemaVersion: 1, payload: { countId: selected.count.id, lineId: countLine, countedQuantity: Number(countQuantity) }, attachmentReferences: [], dependencyIds: [] }), "Count saved locally. No stock has moved; the server must accept the draft count line."); }}><h3 className="font-medium">Inventory count</h3><select className="w-full rounded-md border bg-background p-2" value={countLine} onChange={(event) => setCountLine(event.target.value)} required><option value="">Choose a draft count line</option>{countLines.map(({ count, line }) => <option key={string(line.id)} value={string(line.id)}>{string(object(count.warehouse)?.name)}: {string(object(line.item)?.name)}</option>)}</select><Input type="number" min="0" step="1" value={countQuantity} onChange={(event) => setCountQuantity(event.target.value)} placeholder="Counted quantity" required /><Button disabled={busy}>Save pending count</Button></form> : null}
    {schoolPack ? <form className="space-y-3 rounded-lg border p-4" onSubmit={(event) => { event.preventDefault(); void save(() => captureOfflineOperation(organizationId, userId, { module: "school", entityType: "school.attendance", entityId: `${schoolStudent}:${schoolDate}`, operationType: "record", baseServerVersion: schoolPack.serverVersion, payloadSchemaVersion: 1, payload: { termId: schoolTerm, classId: schoolClass, date: new Date(`${schoolDate}T00:00:00.000Z`).toISOString(), entries: [{ studentId: schoolStudent, status: attendanceStatus }] }, attachmentReferences: [], dependencyIds: [] }), "Attendance saved locally. Enrollment, correction window, and duplicates will be revalidated by the server."); }}><h3 className="font-medium">School attendance</h3><select className="w-full rounded-md border bg-background p-2" value={schoolTerm} onChange={(event) => setSchoolTerm(event.target.value)} required><option value="">Choose term</option>{terms.map((term) => <option key={string(term.id)} value={string(term.id)}>{string(term.name)}</option>)}</select><select className="w-full rounded-md border bg-background p-2" value={schoolClass} onChange={(event) => { setSchoolClass(event.target.value); setSchoolStudent(""); }} required><option value="">Choose class</option>{classes.map((item) => <option key={string(item.id)} value={string(item.id)}>{string(item.name)}</option>)}</select><select className="w-full rounded-md border bg-background p-2" value={schoolStudent} onChange={(event) => setSchoolStudent(event.target.value)} required><option value="">Choose student</option>{students.map((student) => <option key={string(student.id)} value={string(student.id)}>{string(student.lastName)}, {string(student.firstName)}</option>)}</select><Input type="date" value={schoolDate} onChange={(event) => setSchoolDate(event.target.value)} required /><select className="w-full rounded-md border bg-background p-2" value={attendanceStatus} onChange={(event) => setAttendanceStatus(event.target.value)}>{["PRESENT", "ABSENT", "LATE", "EXCUSED"].map((status) => <option key={status}>{status}</option>)}</select><Button disabled={busy}>Save attendance for later</Button></form> : null}
    {hotelPack ? <form className="space-y-3 rounded-lg border p-4" onSubmit={(event) => { event.preventDefault(); const task = tasks.find((item) => item.id === housekeepingTask); if (!task) return; void save(() => captureOfflineOperation(organizationId, userId, { module: "hotel", entityType: "hotel.housekeeping", entityId: housekeepingTask, operationType: "update", baseServerVersion: version(task.updatedAt, hotelPack.serverVersion), payloadSchemaVersion: 1, payload: { taskId: housekeepingTask, status: housekeepingStatus, assignedTo: task.assignedTo ?? null }, attachmentReferences: [], dependencyIds: [] }), "Housekeeping update saved locally. Room availability changes only after server confirmation."); }}><h3 className="font-medium">Hotel housekeeping</h3><select className="w-full rounded-md border bg-background p-2" value={housekeepingTask} onChange={(event) => setHousekeepingTask(event.target.value)} required><option value="">Choose housekeeping task</option>{tasks.map((task) => <option key={string(task.id)} value={string(task.id)}>Room {string(object(task.room)?.number)}: {string(task.status)}</option>)}</select><select className="w-full rounded-md border bg-background p-2" value={housekeepingStatus} onChange={(event) => setHousekeepingStatus(event.target.value)}>{["IN_PROGRESS", "INSPECTION", "COMPLETED"].map((status) => <option key={status}>{status}</option>)}</select><Button disabled={busy}>Save pending housekeeping update</Button></form> : null}
  </section>;
}
