ALTER TYPE "PosSaleStatus" ADD VALUE IF NOT EXISTS 'SUSPENDED' BEFORE 'COMPLETED';
ALTER TYPE "PosSaleStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_REFUNDED' AFTER 'COMPLETED';
CREATE TYPE "PosReturnStatus" AS ENUM ('COMPLETED', 'VOIDED');
ALTER TABLE "PosSession" ADD COLUMN "expectedCash" DECIMAL(12,2), ADD COLUMN "cashVariance" DECIMAL(12,2), ADD COLUMN "varianceReason" TEXT;
ALTER TABLE "PosSaleLine" ADD COLUMN "skuSnapshot" TEXT, ADD COLUMN "barcodeSnapshot" TEXT, ADD COLUMN "taxRateSnapshot" DECIMAL(7,4) NOT NULL DEFAULT 0, ADD COLUMN "discountSnapshot" DECIMAL(12,2) NOT NULL DEFAULT 0;
CREATE TABLE "PosPayment" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "saleId" TEXT NOT NULL, "method" "PosPaymentMethod" NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "reference" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PosPayment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PosReturn" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "saleId" TEXT NOT NULL, "returnNumber" TEXT NOT NULL, "reason" TEXT NOT NULL, "status" "PosReturnStatus" NOT NULL DEFAULT 'COMPLETED', "refundMethod" "PosPaymentMethod" NOT NULL, "refundAmount" DECIMAL(12,2) NOT NULL, "processedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PosReturn_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PosReturnLine" ("id" TEXT NOT NULL, "returnId" TEXT NOT NULL, "saleLineId" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "unitAmount" DECIMAL(12,2) NOT NULL, "lineAmount" DECIMAL(12,2) NOT NULL, CONSTRAINT "PosReturnLine_pkey" PRIMARY KEY ("id"));
INSERT INTO "PosPayment" ("id", "organizationId", "saleId", "method", "amount", "createdAt") SELECT CONCAT('pospay_', "id"), "organizationId", "id", "paymentMethod", "total", "createdAt" FROM "PosSale" WHERE "status" <> 'VOIDED';
CREATE INDEX "PosPayment_organizationId_method_idx" ON "PosPayment"("organizationId", "method");
CREATE INDEX "PosPayment_saleId_idx" ON "PosPayment"("saleId");
CREATE UNIQUE INDEX "PosReturn_organizationId_returnNumber_key" ON "PosReturn"("organizationId", "returnNumber");
CREATE INDEX "PosReturn_organizationId_createdAt_idx" ON "PosReturn"("organizationId", "createdAt");
CREATE INDEX "PosReturn_saleId_idx" ON "PosReturn"("saleId");
CREATE INDEX "PosReturnLine_returnId_idx" ON "PosReturnLine"("returnId");
CREATE INDEX "PosReturnLine_saleLineId_idx" ON "PosReturnLine"("saleLineId");
ALTER TABLE "PosPayment" ADD CONSTRAINT "PosPayment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PosPayment" ADD CONSTRAINT "PosPayment_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "PosSale"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PosReturn" ADD CONSTRAINT "PosReturn_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PosReturn" ADD CONSTRAINT "PosReturn_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "PosSale"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PosReturnLine" ADD CONSTRAINT "PosReturnLine_returnId_fkey" FOREIGN KEY ("returnId") REFERENCES "PosReturn"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PosReturnLine" ADD CONSTRAINT "PosReturnLine_saleLineId_fkey" FOREIGN KEY ("saleLineId") REFERENCES "PosSaleLine"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
