import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { EntityDialog } from "@/components/forms/entity-dialog";
import { requireModuleAccess } from "@/lib/auth/module-access";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { listEmployees, listTerminationRequests, listOffboardingTasks } from "@/modules/hr/service";
import { db } from "@/lib/db";
import { submitTermination, decideTermination, cancelTerminationRequest, reinstate, toggleOffboardingTask } from "./actions";

function StepUp({ twoFactorEnabled }: { twoFactorEnabled: boolean }) { return <><div><Label>Current administrator password</Label><Input name="currentPassword" type="password" autoComplete="current-password" required /></div>{twoFactorEnabled ? <div><Label>Authenticator code</Label><Input name="twoFactorCode" inputMode="numeric" pattern="[0-9]{6}" required /></div> : null}</>; }
export default async function TerminationsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const params = await searchParams; const tenant = await requireModuleAccess("hr");
  const [employees, requests, user] = await Promise.all([listEmployees(tenant.organizationId), listTerminationRequests(tenant.organizationId), db.user.findUnique({ where: { id: tenant.userId }, select: { twoFactorEnabled: true } })]);
  const taskSets = await Promise.all(requests.filter((r) => ["PENDING", "APPROVED", "EFFECTIVE"].includes(r.status)).map(async (r) => [r.id, await listOffboardingTasks(tenant.organizationId, r.id)] as const)); const tasks = new Map(taskSets);
  const canInitiate = hasPermission(tenant, PERMISSIONS.HR_TERMINATIONS_INITIATE); const canApprove = hasPermission(tenant, PERMISSIONS.HR_TERMINATIONS_APPROVE); const canReinstate = hasPermission(tenant, PERMISSIONS.HR_EMPLOYEES_REINSTATE);
  return <div className="space-y-6"><div className="flex items-center justify-between"><PageHeader title="Termination and offboarding" description="Controlled termination, approval, access, final-pay, offboarding, cancellation, and reinstatement workflows." />{canInitiate ? <EntityDialog trigger={<Button>Start termination</Button>} title="Safe termination workflow" action={submitTermination} submitLabel="Submit termination"><div><Label>Employee</Label><select name="employeeId" className="h-10 w-full rounded-md border bg-background px-3" required>{employees.filter((e) => !["TERMINATED", "TERMINATION_PENDING"].includes(e.status)).map((e) => <option key={e.id} value={e.id}>{e.fullName}</option>)}</select></div><div><Label>Termination category</Label><select name="category" className="h-10 w-full rounded-md border bg-background px-3">{["RESIGNATION","DISMISSAL","REDUNDANCY","RETIREMENT","CONTRACT_COMPLETION","DEATH","OTHER"].map((v) => <option key={v}>{v.replaceAll("_", " ")}</option>)}</select></div><div><Label>Reason</Label><Textarea name="reason" required /></div><div className="grid grid-cols-2 gap-3"><div><Label>Last working date</Label><Input name="lastWorkingDate" type="date" required /></div><div><Label>Effective date</Label><Input name="effectiveDate" type="date" required /></div></div><div><Label>Account access</Label><select name="accessDisposition" className="h-10 w-full rounded-md border bg-background px-3"><option value="SUSPEND_ON_EFFECTIVE_DATE">Suspend on effective date</option><option value="SUSPEND_IMMEDIATELY">Suspend immediately</option><option value="LEAVE_UNCHANGED">Leave unchanged with warning</option></select></div><div className="grid grid-cols-2 gap-3"><div><Label>Final salary</Label><Input name="finalSalary" type="number" step="0.01" /></div><div><Label>Leave encashment</Label><Input name="leaveEncashment" type="number" step="0.01" defaultValue="0" /></div><div><Label>Severance</Label><Input name="severance" type="number" step="0.01" defaultValue="0" /></div><div><Label>Outstanding deductions</Label><Input name="outstandingDeductions" type="number" step="0.01" defaultValue="0" /></div></div><div><Label>Notes</Label><Textarea name="notes" /></div><StepUp twoFactorEnabled={user?.twoFactorEnabled ?? false} /></EntityDialog> : null}</div>
    {params.saved ? <p className="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">HR workflow updated.</p> : null}{params.error ? <p className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">The workflow was blocked. Check permissions, state, password, 2FA, dates, and maker-checker rules.</p> : null}
    <div className="space-y-4">{requests.map((request) => <section key={request.id} className="rounded-xl border p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{request.employee.fullName}</h2><p className="text-sm text-muted-foreground">{request.category.replaceAll("_", " ")} · Effective {request.effectiveDate.toLocaleDateString()}</p><p className="mt-2 text-sm">{request.reason}</p></div><Badge variant={request.status === "EFFECTIVE" ? "destructive" : request.status === "REJECTED" || request.status === "CANCELLED" ? "outline" : "secondary"}>{request.status}</Badge></div>
      <div className="mt-4 flex flex-wrap gap-2">{request.status === "PENDING" && canApprove ? <EntityDialog trigger={<Button size="sm">Review</Button>} title="Review termination" action={decideTermination} submitLabel="Approve"><input type="hidden" name="id" value={request.id} /><p className="text-sm">Maker-checker control blocks the initiator from approving this request.</p><div><Label>Rejection or review note</Label><Textarea name="reason" /></div><StepUp twoFactorEnabled={user?.twoFactorEnabled ?? false} /><div className="flex gap-2"><Button type="submit" name="decision" value="approve">Approve</Button><Button type="submit" name="decision" value="reject" variant="destructive">Reject</Button></div></EntityDialog> : null}{["PENDING","APPROVED"].includes(request.status) && canApprove ? <EntityDialog trigger={<Button size="sm" variant="outline">Cancel termination</Button>} title="Cancel termination" action={cancelTerminationRequest}><input type="hidden" name="id" value={request.id} /><div><Label>Cancellation reason</Label><Textarea name="reason" required /></div><StepUp twoFactorEnabled={user?.twoFactorEnabled ?? false} /></EntityDialog> : null}{request.status === "EFFECTIVE" && canReinstate ? <EntityDialog trigger={<Button size="sm" variant="outline">Reinstate employee</Button>} title="Reinstate employee" action={reinstate}><input type="hidden" name="employeeId" value={request.employeeId} /><div><Label>Reason</Label><Textarea name="reason" required /></div><div><Label>Effective date</Label><Input name="effectiveDate" type="date" required /></div><div><Label>Restored job title</Label><Input name="jobTitle" defaultValue={request.employee.jobTitle ?? ""} /></div><div><Label>Department</Label><Input name="department" defaultValue={request.employee.department ?? ""} /></div><label className="flex gap-2 text-sm"><input type="checkbox" name="payrollEligible" />Eligible for payroll</label><label className="flex gap-2 text-sm"><input type="checkbox" name="restoreAccess" />Restore organization login</label><StepUp twoFactorEnabled={user?.twoFactorEnabled ?? false} /></EntityDialog> : null}</div>
      {(tasks.get(request.id)?.length ?? 0) > 0 ? <div className="mt-5"><h3 className="text-sm font-semibold">Offboarding checklist</h3><div className="mt-2 grid gap-2 md:grid-cols-2">{tasks.get(request.id)?.map((task) => <form key={task.id} action={toggleOffboardingTask} className="flex items-center justify-between rounded-md border p-2 text-sm"><input type="hidden" name="taskId" value={task.id} /><input type="hidden" name="completed" value={String(!task.completed)} /><span className={task.completed ? "line-through text-muted-foreground" : ""}>{task.title}</span><Button type="submit" size="sm" variant="ghost">{task.completed ? "Undo" : "Complete"}</Button></form>)}</div></div> : null}</section>)}</div>
  </div>;
}
