import { Landmark, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EntityDialog } from "@/components/forms/entity-dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PageHeader } from "@/components/layout/page-header";
import { requireModuleAccess } from "@/lib/auth/module-access";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { formatMoney } from "@/lib/currency";
import { getTaxReturnWorkingReport, listTaxCodes, listTaxPeriods } from "@/modules/accounting/tax-service";
import { changeTaxPeriodAction, createTaxCodeAction, createTaxPeriodAction } from "./actions";

const ERRORS: Record<string, string> = { forbidden: "You do not have permission to manage tax records.", invalid: "Enter a valid, non-duplicated tax code and rates.", "invalid-period": "Enter a valid, non-duplicated tax period and due date.", "invalid-state": "The tax-period action is not valid. Lock before filing and include the filing reference." };

export default async function AccountingTaxPage({ searchParams }: { searchParams: Promise<{ period?: string; saved?: string; error?: string }> }) {
  const params = await searchParams;
  const tenant = await requireModuleAccess("accounting");
  const canConfigure = hasPermission(tenant, PERMISSIONS.ACCOUNTING_SETTINGS_MANAGE);
  const canManagePeriods = hasPermission(tenant, PERMISSIONS.ACCOUNTING_PERIODS_MANAGE);
  const [codes, periods, report] = await Promise.all([listTaxCodes(tenant.organizationId), listTaxPeriods(tenant.organizationId), getTaxReturnWorkingReport(tenant.organizationId, params.period)]);
  const money = (value: Parameters<typeof formatMoney>[0]) => formatMoney(value, tenant.organization.currency);
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><PageHeader title="Tax and VAT" description="Effective-dated tax codes, monthly control periods, and a working VAT return supported by transaction evidence." /><div className="flex gap-2">
      {canConfigure ? <EntityDialog trigger={<Button size="sm" variant="outline"><Plus />Tax code</Button>} title="Create tax code" action={createTaxCodeAction}><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Code</Label><Input name="code" placeholder="GH-STD-2027" required /></div><div className="space-y-2"><Label>Jurisdiction</Label><Input name="jurisdiction" defaultValue="GH" required /></div></div><div className="space-y-2"><Label>Name</Label><Input name="name" required /></div><div className="space-y-2"><Label>Treatment</Label><select name="treatment" className="h-10 w-full rounded-md border bg-background px-3"><option value="STANDARD">Standard</option><option value="ZERO_RATED">Zero-rated</option><option value="EXEMPT">Exempt</option><option value="RELIEVED">Relieved</option><option value="OUT_OF_SCOPE">Out of scope</option></select></div><div className="grid gap-4 sm:grid-cols-3"><div><Label>VAT %</Label><Input name="vatRate" type="number" step="0.0001" defaultValue="15" required /></div><div><Label>NHIL %</Label><Input name="nhilRate" type="number" step="0.0001" defaultValue="2.5" required /></div><div><Label>GETFund %</Label><Input name="getfundRate" type="number" step="0.0001" defaultValue="2.5" required /></div></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Effective from</Label><Input name="effectiveFrom" type="date" required /></div><div><Label>Effective to</Label><Input name="effectiveTo" type="date" /></div></div><div className="space-y-2 rounded-md border p-3"><p className="text-sm font-medium">Withholding tax (optional)</p><p className="text-xs text-muted-foreground">Deducted from a supplier at bill-payment time. Confirm the current rate for this category against GRA guidance before use - this is not tax advice.</p><div className="grid gap-4 sm:grid-cols-2"><div><Label>Withholding %</Label><Input name="withholdingRate" type="number" step="0.0001" defaultValue="0" /></div><div><Label>Category</Label><select name="withholdingCategory" className="h-10 w-full rounded-md border bg-background px-3"><option value="">Not applicable</option><option value="GOODS">Goods (5%)</option><option value="SERVICES">Services (7.5%)</option><option value="RENT">Rent (8%)</option></select></div></div></div></EntityDialog> : null}
      {canManagePeriods ? <EntityDialog trigger={<Button size="sm"><Plus />Tax period</Button>} title="Create tax period" action={createTaxPeriodAction}><div className="space-y-2"><Label>Name</Label><Input name="name" placeholder="January 2027 VAT" required /></div><div className="space-y-2"><Label>Jurisdiction</Label><Input name="jurisdiction" defaultValue="GH" required /></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Start</Label><Input name="startDate" type="date" required /></div><div><Label>End</Label><Input name="endDate" type="date" required /></div></div><div><Label>Filing due date</Label><Input name="filingDueDate" type="date" required /></div></EntityDialog> : null}
    </div></div>
    {params.saved ? <div className="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">Saved.</div> : null}{params.error && ERRORS[params.error] ? <div className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{ERRORS[params.error]}</div> : null}
    <div className="rounded-lg border p-4 text-sm"><p className="font-medium">Compliance boundary</p><p className="mt-1 text-muted-foreground">This is a working report, not an electronic GRA filing or tax advice. Reconcile it to source documents, confirm exemptions and retail-scheme approval, then file using the Commissioner-General&apos;s prescribed return.</p><a className="mt-2 inline-block text-primary underline" href="https://gra.gov.gh/domestic-tax/tax-types/vat/" target="_blank" rel="noreferrer">Review current GRA VAT guidance</a></div>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Tax codes</h2><div className="grid gap-3 md:grid-cols-2">{codes.map((code) => <div key={code.id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{code.code}: {code.name}</p><p className="text-sm text-muted-foreground">{code.jurisdiction} · {code.treatment.replaceAll("_", " ")}</p></div>{code.isSystem ? <Badge variant="outline">System</Badge> : null}</div><p className="mt-2 text-sm">VAT {Number(code.vatRate)}% · NHIL {Number(code.nhilRate)}% · GETFund {Number(code.getfundRate)}%</p>{Number(code.withholdingRate) > 0 ? <p className="text-sm">Withholding {Number(code.withholdingRate)}%{code.withholdingCategory ? ` (${code.withholdingCategory.toLowerCase()})` : ""}</p> : null}<p className="text-xs text-muted-foreground">Effective {code.effectiveFrom.toLocaleDateString()}{code.effectiveTo ? ` to ${code.effectiveTo.toLocaleDateString()}` : " onward"}</p></div>)}</div></section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Tax periods and working returns</h2>{periods.length === 0 ? <div className="rounded-lg border p-8 text-center text-muted-foreground"><Landmark className="mx-auto mb-2 size-6" />Create a monthly tax period to produce a working return.</div> : periods.map((period) => <div key={period.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><a className="font-medium text-primary" href={`/app/accounting/tax?period=${period.id}`}>{period.name}</a><Badge variant="outline">{period.status}</Badge></div><p className="text-sm text-muted-foreground">{period.startDate.toLocaleDateString()} to {period.endDate.toLocaleDateString()} · due {period.filingDueDate.toLocaleDateString()}</p>{period.filingReference ? <p className="text-sm">Filing reference: {period.filingReference}</p> : null}</div>{canManagePeriods ? <div className="flex gap-2">{period.status === "OPEN" ? <form action={changeTaxPeriodAction}><input type="hidden" name="id" value={period.id}/><input type="hidden" name="action" value="LOCK"/><Button size="sm" variant="outline">Lock for review</Button></form> : null}{period.status === "LOCKED" ? <><form action={changeTaxPeriodAction}><input type="hidden" name="id" value={period.id}/><input type="hidden" name="action" value="REOPEN"/><Button size="sm" variant="outline">Reopen</Button></form><EntityDialog trigger={<Button size="sm">Mark filed</Button>} title="Record GRA filing acknowledgement" action={changeTaxPeriodAction} submitLabel="Mark filed"><input type="hidden" name="id" value={period.id}/><input type="hidden" name="action" value="FILE"/><div className="space-y-2"><Label>Filing reference</Label><Input name="filingReference" required /></div></EntityDialog></> : null}</div> : null}</div>{report.period?.id === period.id ? <div className="mt-4 grid gap-3 border-t pt-4 sm:grid-cols-3"><div><p className="text-sm text-muted-foreground">Output tax</p><p className="text-xl font-semibold">{money(report.output.totalTax)}</p><p className="text-xs">VAT {money(report.output.vatAmount)} · NHIL {money(report.output.nhilAmount)} · GETFund {money(report.output.getfundAmount)}</p></div><div><p className="text-sm text-muted-foreground">Deductible input tax</p><p className="text-xl font-semibold">{money(report.input.totalTax)}</p><p className="text-xs">VAT {money(report.input.vatAmount)} · NHIL {money(report.input.nhilAmount)} · GETFund {money(report.input.getfundAmount)}</p></div><div><p className="text-sm text-muted-foreground">Net working liability</p><p className="text-xl font-semibold">{money(report.net.totalTax)}</p><p className="text-xs">Based on {report.transactions.length} evidence record(s).</p></div></div> : null}</div>)}</section>
  </div>;
}
